gp7_robot:

  joint_state_controller:
    type : "joint_state_controller/JointStateController"
    publish_rate : 100

  joint_1_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_s_1
    pid : { p : 50, i : 0.0, d : 10}

  joint_2_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_l_2
    pid : { p : 50, i : 0.0, d : 10}

  joint_3_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_u_3
    pid : { p : 50, i : 0.0, d : 10}

  joint_4_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_r_4
    pid : { p : 50, i : 0.0, d : 10}

  joint_5_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_b_5
    pid : { p : 50, i : 0.0, d : 10}

  joint_6_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_t_6
    pid : { p : 50, i : 0.0, d : 10}

  arm_controller:
    type : position_controllers/JointTrajectoryController
    joints : 
      - joint_s_1
      - joint_l_2
      - joint_u_3
      - joint_r_4
      - joint_b_5
      - joint_t_6