gp7_robot:

  joint_state_controller:
    type : "joint_state_controller/JointStateController"
    publish_rate : 100

  joint_1_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_1_s
    pid : { p : 50, i : 0.0, d : 10}

  joint_2_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_2_l
    pid : { p : 50, i : 0.0, d : 10}

  joint_3_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_3_u
    pid : { p : 50, i : 0.0, d : 10}

  joint_4_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_4_r
    pid : { p : 50, i : 0.0, d : 10}

  joint_5_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_5_b
    pid : { p : 50, i : 0.0, d : 10}

  joint_6_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_6_t
    pid : { p : 50, i : 0.0, d : 10}

  arm_controller:
    type : position_controllers/JointTrajectoryController
    joints : 
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t